### ISSUE TITLE
mock 是在哪引入的呢？没看见呢

### ISSUE THREAD

**Issue by ndwgg** [ecstAsy/Taro-Mock#18]

**Comment by h-ecstasy** [comment]
mock 数据是 mockjs 生成的 都在mock 文件夹里面
本地重新开一个窗口执行命令来启动 mock 服务 相当于两个端口运行

**Comment by ndwgg** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by ndwgg** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
